language: ruby
sudo: false

before_install: gem update bundler --no-document

rvm:
  - 2.6.3
  - 2.5.5
  - 2.4.6
  - 2.3.8
  - 2.2.10
  - 2.1.10
  - 2.0.0
  - 1.9.3
  - rbx-2
  - jruby-9.2.7.0

gemfile:
  - Gemfile

branches:
  only:
    - master

script: "bundle exec rake test"

matrix:
  allow_failures:
    - rvm: rbx-2
